[package]
name = "protocol-monitor"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
multiversx-sc = "0.47.0"
multiversx-sc-modules = "0.47.0"

[dev-dependencies]
multiversx-sc-scenario = "0.47.0"
